openapi: 3.0.0
info:
  version: 1.0.0
  title: Alcoholic APIs
  description: Alcoholic API 문서입니다
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
tags:
  - name: auth
    description: 로그인 관련
  - name: alc-type
    description: 알코올 타입
  - name: alc-history
    description: 알코올 히스토리
  - name: alc-recipe
    description: 알코올 레시피
paths:
  $ref: "./paths/_index.yaml"
components:
  parameters: null
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          example:
            data:
              data:
                code: 400
                message: 잘못된 요청
                data: null
    Unauthorized:
      description: 토큰 값이 유효하지 않습니다.
      content:
        application/json:
          example:
            data:
              data:
                code: 401
                message: 토큰 값이 유효하지 않습니다.
                data: null
  securitySchemes:
    AccessToken:
      type: apiKey
      in: header
      name: access-token
security:
  - AccessToken: []
